### ISSUE TITLE
Node Tokens Not Working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/token_block#1]
1) I created a fresh dev site with dev branch of 1.24.x
2) I created a layout with path node/%
3) I enabled the Token Block module
4) On my new layout - I added a block "Tokens for node entities"
5) I added these two tokens

![image](https://user-images.githubusercontent.com/3144571/192941264-27b369f2-7ca7-42c3-ac9c-3e0fe67ddef4.png)

6) This is the results for `/posts/your-first-post`

![image](https://user-images.githubusercontent.com/3144571/192941334-e728639c-d2c4-4cf6-95f7-7da95b358a0a.png)

**Comment by stpaultim** [comment]
Note: I'm having the same problem with this module as I reported for Node Property Block.
https://github.com/backdrop-contrib/node_property_block/issues/2

**Comment by kswan** [comment]
I just tested this module and had a similar (but, interestingly, not the same result as @stpaultim).

Here is the content I added to a "Tokens for node entries" block.
![image](https://user-images.githubusercontent.com/154391/193032206-decc5164-ca41-42cd-ada8-d3a26b2e8df1.png)

Here is the result on a node page.
![image](https://user-images.githubusercontent.com/154391/193032315-e7f73fb4-bb18-4815-9b86-8b470a39e19c.png)

I also tried the following tokens:
[node:author]
[node:created]

**Comment by argiepiano** [comment]
Yes, this is a bug and will be fix shortly. Thanks for reporting!

**Comment by argiepiano** [comment]
@stpaultim @kswan I believe I have fixed the issue. 

Can you please test the latest release? Thanks again for testing!

**Comment by kswan** [comment]
@argiepiano 1.0.1-alpha works for me. Thank you!!

**Comment by stpaultim** [comment]
@argiepiano - I just want to confirm that the module is now working for me as well. 

Excellent work.
