### ISSUE TITLE
Uninstall error

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/token_block#5]
When Token Block is uninstalled I get an error
Error
Class 'TokenBlock' not found

The watchdog log shows:
Error: Class 'TokenBlock' not found in layout_create_handler() (line 1768 of /srv/www/sewscms-8080/core/modules/layout/layout.module).

**Comment by argiepiano** [comment]
That's because you still have that block in the layout. Remove the block from the layout and then uninstall.

I believe this happens with all contrib modules that provide blocks: if you uninstall the module but the block is still in the layout, you'll get an error.

**Comment by kswan** [comment]
Correct. I think I removed the block, but forgot to save the layout.
