### ISSUE TITLE
Provide alternative help or suggestions for available tokens

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/token_block#6]
@argiepiano - I know that you are aware of the problem. It's not clear to me if this is a problem you can fix or if it's a larger issue in core. But, I'd like to suggest some temporary/partial solutions in the meantime. 

```
The admin dialog for the block includes a link to the available token tree. 
Notice that, because the dialog is currently displayed in a modal window, 
the token tree may display in incomplete fashion. This is known issue that 
has not been addressed yet.
```

Could we put any contextual help test to remind the user than the list of available tokens is incomplete and/or point them at some documentation that would help them find/create the tokens they need. 

Just a thought. 

![image](https://user-images.githubusercontent.com/3144571/193183490-43ab7cdd-4dd2-4708-92e3-50878b755b14.png)

**Comment by argiepiano** [comment]
thanks, @stpaultim. That was actually a bug. I just merged a fix and will to a new release soon
